name: Full Stack Deployment Pipeline

on:
  push:
    branches:
      - frontend
      - backend

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
          source: public/
        env:
          AWS_S3_BUCKET: protial-prod-s3-b
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  backend_build_and_deploy:
    name: Backend Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: your-ecr-registry-url
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image to ECR
        run: |
          # Add commands to build your Docker image for the backend
          # Example: docker build -t your-image-name .
          # Example: docker tag your-image-name:latest your-ecr-registry-url/your-image-name:latest
          # Example: docker push your-ecr-registry-url/your-image-name:latest
