name: Full Stack Deployment Pipeline

on:
  push:
    branches:
      - frontend
      - backend

jobs:
  frontend_build_and_deploy:
    name: Frontend Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Install project dependencies before building

      - name: Build frontend
        run: npm run build  # Run the build command to generate build artifacts

      - name: Upload frontend to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
          source: build/  # Specify the path to the build directory
        env:
          AWS_S3_BUCKET: protial-prod-s3-b
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  backend_build_and_deploy:
    name: Backend Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: your-ecr-registry-url
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image to ECR
        run: |
          # Add commands to build your Docker image for the backend
          # Example: docker build -t your-image-name .
          # Example: docker tag your-image-name:latest your-ecr-registry-url/your-image-name:latest
          # Example: docker push your-ecr-registry-url/your-image-name:latest
